[package]
name = "arduino-sys"
version = "0.1.0"
authors = ["Matt Coffin <mcoffin13@gmail.com>"]
build = "build.rs"
links = "arduino"

[dependencies.core]
git = "git://github.com/hackndev/rust-libcore.git"

[build-dependencies]
pkg-config = "0.3"
